apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: danish-survival
  namespace: tfb-servers
  labels:
    run: danish-survival
    backstage.io/kubernetes-id: danish-survival
spec:
  serviceName: "danish-survival"
  replicas: 1
  selector:
    matchLabels:
      run: danish-survival
  template:
    metadata:
      labels:
        run: danish-survival
        backstage.io/kubernetes-id: danish-survival
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        topology.kubernetes.io/region: dc6
      containers:
      - name: danish-survival
        image: harbor.theflyingbirds.net/tfb-servers/danish-survival:latest
        tty: true
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "MEMORY"
            value: "4G"
          - name: "REPLACE_ENV_VARIABLE_PREFIX"
            value: "TFB_"
          - name: "REPLACE_ENV_IN_PLACE"
            value: "true"
        envFrom:
          - secretRef:
              name: world-danish-survival-seed-secret
          - secretRef:
              name: world-danish-survival-nether-seed-secret
        ports:
          - containerPort: 30005
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        # args: ["tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: danish-survival-world
            mountPath: /data/world_danish_survival
          - name: danish-survival-world-nether
            mountPath: /data/world_danish_survival_nether
          - name: danish-survival-world-the-end
            mountPath: /data/world_danish_survival_the_end
          - name: plugins-essentials-userdata
            mountPath: /data/plugins/Essentials/userdata
          - name: plugins-essentials-warps
            mountPath: /data/plugins/Essentials/warps
          - name: plugins-worldguard-worlds
            mountPath: /data/plugins/WorldGuard/worlds
        resources:
          requests:
            memory: "6Gi"
            cpu: "4000m"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30005" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30005"]
          initialDelaySeconds: 120
          periodSeconds: 60
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: danish-survival-world
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: danish-survival-world-nether
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: danish-survival-world-the-end
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: plugins-essentials-userdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: plugins-essentials-warps
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: plugins-worldguard-worlds
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi