apiVersion: v1
kind: Service
metadata:
  name: danish-survival
  namespace: tfb-servers
  labels:
    backstage.io/kubernetes-id: danish-survival
spec:
  type: ClusterIP
  ports:
  - name: danish-survival
    port: 30005
    targetPort: 30005
  selector:
    run: danish-survival