name: Build and deploy TFB server

on:
  workflow_call:
    # inputs:
    #   REGISTRY_URL:
    #     required: true
    #   REGISTRY_USERNAME:
    #     required: true
    #   REGISTRY_TOKEN:
    #     required: true
    #   REGISTRY_REPO:
    #     required: true

jobs:
  build:
    runs-on: debian

    steps:
      # Check out the repository containing the shared Dockerfile
      - name: Checkout shared Dockerfile repository
        uses: actions/checkout@v4
        with:
          repository: forge.theflyingbirds.net/tfb/network
          path: network

      # Check out the Minecraft server repository
      - name: Checkout TFB server repository
        uses: actions/checkout@v4
        with:
          path: server

      - uses: https://github.com/actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: https://github.com/gradle/actions/setup-gradle@v6

      - name: Execute Gradle build
        env:
          MAVEN_URL: forge.theflyingbirds.net
          MAVEN_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
        run: cd ${{ github.workspace }}/server && gradle update --no-build-cache

      - name: Docker CLI installation
        run: |
          apt update
          apt install -y ca-certificates curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
    
      # Login to TFB Registry
      - name: Login to TFB Docker Registry
        uses: docker/login-action@v3
        with:
          registry: forge.theflyingbirds.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          push: true
          tags: forge.theflyingbirds.net/tfb/dev:latest
          labels: org.opencontainers.image.source=https://forge.theflyingbirds.net/tfb/network

      # Build TFB Docker image
      - name: Build Docker image
        run: docker build -t forge.theflyingbirds.net/${{ forge.repository }}:latest -f ${{ forge.workspace }}/network/.forgejo/docker/Dockerfile ${{ forge.workspace }}/server --no-cache