name: Build and deploy TFB server

on:
  workflow_call:
    inputs:
      TFB_REGISTRY_USERNAME:
        required: true
        type: string
      TFB_REGISTRY_TOKEN:
        required: true
        type: string

jobs:
  build:
    runs-on: debian

    steps:
      # Check out the repository containing the shared Dockerfile
      - name: Checkout shared Dockerfile repository
        uses: actions/checkout@v6
        with:
          repository: TFB/network
          ref: main
          path: network

      # Check out the Minecraft server repository
      - name: Checkout TFB server repository
        uses: actions/checkout@v4
        with:
          path: server

      - uses: https://github.com/actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Gradle
        run: |
          apt-get update
          apt-get install -y gradle

      - name: Execute Gradle build
        working-directory: server
        env:
          TFB_REGISTRY_USERNAME: ${{ inputs.TFB_REGISTRY_USERNAME }}
          TFB_REGISTRY_TOKEN: ${{ inputs.TFB_REGISTRY_TOKEN }}
        run: gradle update --no-build-cache

      - name: Docker CLI installation
        run: |
          apt update
          apt install -y ca-certificates curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
    
      # Login to TFB Registry
      - name: Login to TFB Docker Registry
        uses: https://github.com/docker/login-action@v4
        with:
          registry: forge.theflyingbirds.net
          username: ${{ secrets.TFB_REGISTRY_USERNAME }}
          password: ${{ secrets.TFB_REGISTRY_TOKEN }}
          logout: true

      - name: Convert repository name to lowercase
        id: lowercase
        run: |
          repo="$(echo "${{ forge.repository }}" | tr '[:upper:]' '[:lower:]')"
          echo "repo=$repo" >> "$FORGEJO_OUTPUT"

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: forge.theflyingbirds.net/${{ steps.lowercase.outputs.repo }}:latest
          labels: org.opencontainers.image.source=https://forge.theflyingbirds.net/${{ steps.lowercase.outputs.repo }}
          