apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy
  namespace: tfb-network
  labels:
    run: proxy
    backstage.io/kubernetes-id: proxy
spec:
  serviceName: "proxy"
  replicas: 1
  selector:
    matchLabels:
      run: proxy
  template:
    metadata:
      labels:
        run: proxy
        backstage.io/kubernetes-id: proxy
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        "topology.kubernetes.io/region": hel1
        "kubernetes.io/hostname": tfb-root-eu
      containers:
      - name: proxy
        image: docker.theflyingbirds.net/tfb-network/proxy:latest
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: CUSTOM_SERVER
            value: "server.jar"
          - name: EULA
            value: "TRUE"
        ports:
          - containerPort: 25565
            hostPort: 25565
          - containerPort: 8804
          - containerPort: 8192
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: proxy-pv
            mountPath: /data/logs
        resources:
          requests:
            memory: "4Gi"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "proxy-0", "--port", "25565"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "proxy-0", "--port", "25565"]
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 20
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: proxy-pv
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi