apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danish-survival
  namespace: argocd
spec:
  project: tfb-servers
  source:
    repoURL: https://github.com/theflyingbirdsmc/TFB-Network.git
    path: network/danish-survival
  destination:
    server: https://kubernetes.default.svc
    namespace: tfb-servers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true