apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxy
  namespace: argocd
spec:
  project: tfb-servers
  source:
    repoURL: https://github.com/theflyingbirdsmc/proxy.git
    path: proxy