---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: tfb-servers
  annotations:
    backstage.io/kubernetes-id: proxy
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  labels:
    backstage.io/kubernetes-id: proxy
spec:
  type: LoadBalancer 
  externalTrafficPolicy: Local
  # loadBalancerIP: 95.217.44.106
  ports:
    - name: minecraft
      port: 25588
      targetPort: 25588
    - name: plan
      port: 8804
      targetPort: 8804
    - name: votifier
      port: 8192
      targetPort: 8192
  selector:
    run: proxy

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy
  namespace: tfb-servers
  labels:
    run: proxy
    backstage.io/kubernetes-id: proxy
spec:
  serviceName: "proxy"
  replicas: 1
  selector:
    matchLabels:
      run: proxy
  template:
    metadata:
      labels:
        run: proxy
        backstage.io/kubernetes-id: proxy
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        image: docker.theflyingbirds.net/tfb-servers/proxy:latest
        ports:
          - containerPort: 25588
          - containerPort: 8804
          - containerPort: 8192
        command: ["/bin/sh",]
        args: [ "-c", "apt-get update && apt-get install -y screen && screen -dmS minecraft /usr/bin/run-bungeecord.sh && tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: proxy-pv
            mountPath: /tfb
        resources:
          requests:
            memory: "4Gi"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
          initialDelaySeconds: 120
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: proxy-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tfb-network-db
  namespace: tfb-servers
spec:
  serviceName: "tfb-network-db"
  replicas: 1
  selector:
    matchLabels:
      app: tfb-network-db
  template:
    metadata:
      labels:
        app: tfb-network-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.1.2-jammy
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: tfb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/mariadb.conf.d/99-bind-address.cnf
          subPath: my.cnf
      volumes:
      - name: config-volume
        configMap:
          name: mariadb-config
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tfb-network-db
  namespace: tfb-servers
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: tfb-network-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: tfb-servers
data:
  my.cnf: |
    [mysqld]
    max_allowed_packet=16M
    max_connections=100000
    bind-address=*
    [Service]
    LimitNOFILE=10000000
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: tfb-servers
type: Opaque
data:
  root-password: RWF0TXlTaDBydHM=
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plan-ingress
  namespace: tfb-servers
  annotations:
    cert-manager.io/cluster-issuer: theflyingbirds-prod
spec:
  tls:
  - hosts:
    - stats.theflyingbirds.net
    secretName: plan-tls
  rules:
  - host: stats.theflyingbirds.net
    http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 8804
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votifier-ingress
  namespace: tfb-servers
  annotations:
    cert-manager.io/cluster-issuer: theflyingbirds-prod
spec:
  tls:
  - hosts:
    - mc.theflyingbirds.net
    secretName: votifier-tls
  rules:
  - host: mc.theflyingbirds.net
    http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 8192
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flamecord-ingress
  namespace: tfb-servers
  annotations:
    cert-manager.io/cluster-issuer: theflyingbirds-prod
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
spec:
  rules:
  - host: mc.theflyingbirds.net
    http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 25588
        path: /
        pathType: Prefix