apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs-tmm
  namespace: tfb-network
  labels:
    run: cs-tmm
    backstage.io/kubernetes-id: cs-tmm
spec:
  serviceName: cs-tmm
  replicas: 1
  selector:
    matchLabels:
      run: cs-tmm
  template:
    metadata:
      labels:
        run: cs-tmm
        backstage.io/kubernetes-id: cs-tmm
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        "topology.kubernetes.io/region": hel1
        "kubernetes.io/hostname": tfb-root-eu
      containers:
      - name: cs-tmm
        image: docker.theflyingbirds.net/tfb-network/cs-tmm:latest
        tty: true
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "REPLACE_ENV_VARIABLE_PREFIX"
            value: "TFB_"
          - name: "REPLACE_ENV_IN_PLACE"
            value: "true"
          - name: "MEMORY"
            value: "8G"
        envFrom:
          - secretRef:
              name: cs-tmm-discord-token
          - secretRef:
              name: world-cs-tmm-seed
        ports:
          - containerPort: 30100
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        # args: ["tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: world-cs-tmm
            mountPath: /data/world_cs_tmm
          - name: world-cs-tmm-nether
            mountPath: /data/world_cs_tmm_nether
          - name: world-cs-tmm-the-end
            mountPath: /data/world_cs_tmm_the_end
          - name: plugins-essentials-userdata
            mountPath: /data/plugins/Essentials/userdata
          - name: plugins-essentials-warps
            mountPath: /data/plugins/Essentials/warps
          - name: plugins-worldguard-worlds
            mountPath: /data/plugins/WorldGuard/worlds
        resources:
          requests:
            memory: "8Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 30100
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 30100
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 2
        startupProbe:
          tcpSocket:
            port: 30100
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: world-cs-tmm
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi
  - metadata:
      name: world-cs-tmm-nether
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: world-cs-tmm-the-end
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: plugins-essentials-userdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: plugins-essentials-warps
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: plugins-worldguard-worlds
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi