apiVersion: v1
kind: Service
metadata:
  name: cs-tmm
  namespace: tfb-servers
  labels:
    backstage.io/kubernetes-id: cs-tmm
spec:
  type: ClusterIP
  ports:
  - name: cs-tmm
    port: 30005
    targetPort: 30005
  selector:
    run: cs-tmm