apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs-tmm
  namespace: tfb-network
  labels:
    run: cs-tmm
    backstage.io/kubernetes-id: cs-tmm
spec:
  serviceName: cs-tmm
  replicas: 1
  selector:
    matchLabels:
      run: cs-tmm
  template:
    metadata:
      labels:
        run: cs-tmm
        backstage.io/kubernetes-id: cs-tmm
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        topology.kubernetes.io/region: hel1
      containers:
      - name: cs-tmm
        image: harbor.theflyingbirds.net/tfb-network/cs-tmm:latest
        tty: true
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "MEMORY"
            value: "4G"
        ports:
          - containerPort: 30100
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: world-cs-tmm
            mountPath: /data/world_cs_tmm
          - name: world-cs-tmm-nether
            mountPath: /data/world_cs_tmm_nether
          - name: world-cs-tmm-the-end
            mountPath: /data/world_cs_tmm_the_end
          - name: plugins-essentials-userdata
            mountPath: /data/plugins/Essentials/userdata
          - name: plugins-essentials-warps
            mountPath: /data/plugins/Essentials/warps
          - name: plugins-worldguard-worlds
            mountPath: /data/plugins/WorldGuard/worlds
        resources:
          requests:
            memory: "6Gi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30100" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30100"]
          initialDelaySeconds: 120
          periodSeconds: 60
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: world-cs-tmm
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi
  - metadata:
      name: world-cs-tmm-nether
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: world-cs-tmm-the-end
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: plugins-essentials-userdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: plugins-essentials-warps
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: plugins-worldguard-worlds
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi