apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs-tmm
  namespace: tfb-servers
  labels:
    run: cs-tmm
    backstage.io/kubernetes-id: cs-tmm
spec:
  serviceName: "cs-tmm"
  replicas: 1
  selector:
    matchLabels:
      run: cs-tmm
  template:
    metadata:
      labels:
        run: cs-tmm
        backstage.io/kubernetes-id: cs-tmm
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: cs-tmm
        image: harbor.theflyingbirds.net/tfb-servers/cs-tmm:latest
        tty: true
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "MEMORY"
            value: "4G"
        ports:
          - containerPort: 30005
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: cs-tmm-world-pv
            mountPath: /data/world_danish_survival
        resources:
          requests:
            memory: "6Gi"
            cpu: "4000m"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30005" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30005"]
          initialDelaySeconds: 120
          periodSeconds: 60
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: cs-tmm-world-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi