-- LUCKPERMS --
DROP USER IF EXISTS 'tfb_luckperms';
CREATE USER 'tfb_luckperms'@'%';
CREATE DATABASE IF NOT EXISTS s1_luckperms;
GRANT ALL ON s1_luckperms.* TO 'tfb_luckperms'@'%' IDENTIFIED BY 'uEJq!fjGM!62*&cmX*mBRhT9L2@SgX';

-- PLAN --
DROP USER IF EXISTS 'u1_IfPFyakFRt'; 
CREATE USER 'u1_IfPFyakFRt'@'%';
CREATE DATABASE IF NOT EXISTS s1_plan;
GRANT ALL ON s1_plan.* TO 'u1_IfPFyakFRt'@'%' IDENTIFIED BY 'kccEHEZYlXDPh.3!JW84dyHp';

-- VOTINGPLUGIN --
DROP USER IF EXISTS 'u1_ouoD9Ps4h4';
CREATE USER 'u1_ouoD9Ps4h4'@'%';
CREATE DATABASE IF NOT EXISTS s1_votingplugin;
GRANT ALL ON s1_votingplugin.* TO 'u1_ouoD9Ps4h4'@'%' IDENTIFIED BY 'dZ4VQh4VogXkhwB@!Cr3oFO+';

-- GADGETSMENU --
DROP USER IF EXISTS 'u2_oeN5DZ9Msp';
CREATE USER 'u2_oeN5DZ9Msp'@'%';
CREATE DATABASE IF NOT EXISTS s2_gadgetsmenu;
GRANT ALL ON s2_gadgetsmenu.* TO 'u2_oeN5DZ9Msp'@'%' IDENTIFIED BY '^DqHSSNgoX.IQCre6=.x2.J4';

-- CHATCONTROLRED --
DROP USER IF EXISTS 'u2_FqhK8IpLLx';
CREATE USER 'u2_FqhK8IpLLx'@'%';
CREATE DATABASE IF NOT EXISTS s2_chatcontrolred;
GRANT ALL ON s2_chatcontrolred.* TO 'u2_FqhK8IpLLx'@'%' IDENTIFIED BY 'rJx!vY=aUNPZ2@c=PRjwZshm';

-- PLOTSQUARED --
DROP USER IF EXISTS 'u5_DEXeIJnxSl';
CREATE USER 'u5_DEXeIJnxSl'@'%';
CREATE DATABASE IF NOT EXISTS s5_plotsquared;
GRANT ALL ON s5_plotsquared.* TO 'u5_DEXeIJnxSl'@'%' IDENTIFIED BY 'x2IQ^K4prZAW=^uTzpGMMG@u';

-- COREPROTECT --
DROP USER IF EXISTS 'u9_OuEs5LpxqL';
CREATE USER 'u9_OuEs5LpxqL'@'%';
CREATE DATABASE IF NOT EXISTS s9_coreprotect;
GRANT ALL ON s9_coreprotect.* TO 'u9_OuEs5LpxqL'@'%' IDENTIFIED BY '9l!C+mt2.4MvHb+BqnVkEU+f';
FLUSH PRIVILEGES;

-- PLAYERREFERALS --
DROP USER IF EXISTS 'u2_wdkOuuJO27';
CREATE USER 'u2_wdkOuuJO27'@'%';
CREATE DATABASE IF NOT EXISTS s2_playerreferals;
GRANT ALL ON s2_playerreferals.* TO 'u2_wdkOuuJO27'@'%' IDENTIFIED BY 'EDMgT5VOIaSa0TWw@b9LeuXW';
FLUSH PRIVILEGES;

-- HEXNICKS --
DROP USER IF EXISTS 'u2_js3sZ1TlmU';
CREATE USER 'u2_js3sZ1TlmU'@'%';
CREATE DATABASE IF NOT EXISTS s2_hexnicks;
GRANT ALL ON s2_hexnicks.* TO 'u2_js3sZ1TlmU'@'%' IDENTIFIED BY '^zbJ!kcND3w!UAjkdQZofY5=';