apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby
  namespace: tfb-network
  labels:
    run: lobby
    backstage.io/kubernetes-id: lobby
spec:
  serviceName: "lobby"
  replicas: 1
  selector:
    matchLabels:
      run: lobby
  template:
    metadata:
      labels:
        run: lobby
        backstage.io/kubernetes-id: lobby
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        "topology.kubernetes.io/region": hel1
        "kubernetes.io/hostname": bm-tfb-cluster-2675687
      containers:
      - name: lobby
        image: docker.theflyingbirds.net/tfb-network/lobby:latest
        # image: itzg/minecraft-server:java21
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "EULA"
            value: "TRUE"
          - name: "MEMORY"
            value: "4G"
          # - name: "EXTRA_ARGS"
          #   value: "--DPaper.WorkerThreadCount=#"
        ports:
          - containerPort: 30001
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        # args: ["tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: lobby-world-pv
            mountPath: /data/world_lobby
        resources:
          requests:
            memory: "4Gi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 30001
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 30001
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 2
        startupProbe:
          tcpSocket:
            port: 30001
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: lobby-world-pv
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOncePod"]
      resources:
        requests:
          storage: 5Gi