apiVersion: v1
kind: Service
metadata:
  name: lobby
  namespace: tfb-servers
  labels:
    backstage.io/kubernetes-id: lobby
spec:
  type: ClusterIP
  ports:
  - name: lobby
    port: 30001
    targetPort: 30001
  selector:
    run: lobby