apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby
  namespace: tfb-servers
  labels:
    run: lobby
    backstage.io/kubernetes-id: lobby
spec:
  serviceName: "lobby"
  replicas: 1
  selector:
    matchLabels:
      run: lobby
  template:
    metadata:
      labels:
        run: lobby
        backstage.io/kubernetes-id: lobby
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        topology.kubernetes.io/region: dc6
      containers:
      - name: lobby
        image: harbor.theflyingbirds.net/tfb-servers/lobby:latest
        tty: true
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "USE_AIKAR_FLAGS"
            value: "true"
          - name: "MEMORY"
            value: "8G"
        ports:
          - containerPort: 30001
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: lobby-world-pv
            mountPath: /data/world_lobby
        resources:
          requests:
            memory: "8Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30001" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost", "--port", "30001"]
          initialDelaySeconds: 120
          periodSeconds: 60
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: lobby-world-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi