apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: creative
  namespace: tfb-network
  labels:
    run: creative
    backstage.io/kubernetes-id: creative
spec:
  serviceName: creative
  replicas: 1
  selector:
    matchLabels:
      run: creative
  template:
    metadata:
      labels:
        run: creative
        backstage.io/kubernetes-id: creative
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        "kubernetes.io/hostname": bm-tfb-cluster-2675687
      containers:
      - name: creative
        image: docker.theflyingbirds.net/tfb-network/creative:latest
        tty: true
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: "CUSTOM_SERVER"
            value: "server.jar"
          - name: "EXEC_DIRECTLY"
            value: "false"
          - name: "ENABLE_RCON"
            value: "false"
          - name: "REPLACE_ENV_VARIABLE_PREFIX"
            value: "TFB_"
          - name: "REPLACE_ENV_IN_PLACE"
            value: "true"
          - name: "MEMORY"
            value: "4G"
        # envFrom:
        #   - secretRef:
        #       name: creative-discord-token
        #   - secretRef:
        #       name: world-creative-seed
        ports:
          - containerPort: 30101
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y screen && screen -dmS minecraft /start && tail -f /dev/null"]
        # args: ["tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: world-creative
            mountPath: /data/world_creative
          - name: plugins-essentials-userdata
            mountPath: /data/plugins/Essentials/userdata
          - name: plugins-essentials-warps
            mountPath: /data/plugins/Essentials/warps
          - name: plugins-worldguard-worlds
            mountPath: /data/plugins/WorldGuard/worlds
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 30101
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 30101
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 2
        startupProbe:
          tcpSocket:
            port: 30101
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: world-creative
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 25Gi
  - metadata:
      name: plugins-essentials-userdata
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: plugins-essentials-warps
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: plugins-worldguard-worlds
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi